version: '3'
services:
  app:
    build: .
    volumes:
      - ${HF_HOME:-~/.cache/huggingface/hub}:/app/.cache/huggingface/hub
    environment:
      - HF_HOME=/app/.cache/huggingface/hub
    command: ["uvicorn", "app.main:app", "--reload", "--host", "0.0.0.0"]
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]